variable "oci_tenancy" {}
variable "oci_user" {}
variable "oci_fingerprint" {}
variable "oci_key" {}
variable "oci_region" {}
variable "compartment_id" {}
variable "compartment_description" {}
variable "compartment_name" {}
variable "vcn_cidr_block" {}
variable "app_vcn_name" {}
variable "public_route_table_route_rules_destination" {}
variable "public_route_table_route_rules_destination_type" {}
variable "public_subnet_cidr_block" {}
variable "public_subnet_display_name" {}
variable "public_subnet_route_table_name" {}
variable "IGW_name" {}
variable "public_subnet_sl_name" {}
variable "egress_sl_protocol" {}
variable "egress_sl_destination" {}
variable "ingress_sl_source_all_cidr" {}
variable "ingress_sl_source_my_ip" {}
variable "instance_availability_domain" {}
variable "app_instance_shape" {}
variable "app_instance_display_name" {}
variable "instance_os" {}
variable "linux_os_version" {}
variable "os_shape" {}
variable "path_local_public_key" { sensitive = true }