variable "compartment_id" {}
variable "vcn_cidr_block" {}
variable "app_vcn_name" {}
variable "public_route_table_route_rules_destination" {}
variable "public_route_table_route_rules_destination_type" {}
variable "public_subnet_cidr_block" {}
variable "public_subnet_display_name" {}
variable "public_subnet_route_table_name" {}
variable "IGW_name" {}
variable "public_subnet_sl_name" {}
variable "egress_sl_protocol" {}
variable "egress_sl_destination" {}
variable "ingress_sl_source_all_cidr" {}
variable "ingress_sl_source_my_ip" {}
